# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1207NxoqlqWJxbYcMP5W7rhKYTWd5NEPp
"""

"""
HealthAI Pneumonia Classifier - Google Colab Ready
Run this notebook on Google Colab with GPU enabled for best performance
"""

# ============================================================================
# SECTION 1: SETUP AND INSTALLATION
# ============================================================================

# Install required packages (run this cell first in Colab)
"""
!pip install torch torchvision pillow scikit-learn matplotlib
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix
import matplotlib.pyplot as plt
from google.colab import files
import zipfile

# ============================================================================
# SECTION 2: DATA DOWNLOAD (Kaggle Dataset)
# ============================================================================

def download_kaggle_dataset():
    """
    Download Chest X-Ray Pneumonia dataset from Kaggle
    Requires Kaggle API credentials
    """
    # Upload kaggle.json
    print("Please upload your kaggle.json file:")
    uploaded = files.upload()

    # Setup Kaggle API
    os.makedirs('/root/.kaggle', exist_ok=True)
    os.system('mv kaggle.json /root/.kaggle/')
    os.system('chmod 600 /root/.kaggle/kaggle.json')

    # Download dataset
    print("\nDownloading dataset...")
    os.system('kaggle datasets download -d paultimothymooney/chest-xray-pneumonia')

    # Extract dataset
    print("\nExtracting dataset...")
    with zipfile.ZipFile('chest-xray-pneumonia.zip', 'r') as zip_ref:
        zip_ref.extractall('data')

    print("Dataset ready!")
    return 'data/chest_xray'

# Alternative: Mount Google Drive
def mount_drive():
    """Mount Google Drive to access your data"""
    from google.colab import drive
    drive.mount('/content/drive')
    print("Google Drive mounted!")
    # Your data path: '/content/drive/MyDrive/your_folder'

# ============================================================================
# SECTION 3: DATASET CLASS
# ============================================================================

class ChestXrayDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        """
        Args:
            root_dir: Directory with NORMAL and PNEUMONIA subdirectories
            transform: Optional transform to be applied on images
        """
        self.root_dir = root_dir
        self.transform = transform
        self.images = []
        self.labels = []

        # Load NORMAL images (label 0)
        normal_dir = os.path.join(root_dir, 'NORMAL')
        if os.path.exists(normal_dir):
            for img_name in os.listdir(normal_dir):
                if img_name.endswith(('.png', '.jpg', '.jpeg')):
                    self.images.append(os.path.join(normal_dir, img_name))
                    self.labels.append(0)

        # Load PNEUMONIA images (label 1)
        pneumonia_dir = os.path.join(root_dir, 'PNEUMONIA')
        if os.path.exists(pneumonia_dir):
            for img_name in os.listdir(pneumonia_dir):
                if img_name.endswith(('.png', '.jpg', '.jpeg')):
                    self.images.append(os.path.join(pneumonia_dir, img_name))
                    self.labels.append(1)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        image = Image.open(img_path).convert('RGB')
        label = self.labels[idx]

        if self.transform:
            image = self.transform(image)

        return image, label

# ============================================================================
# SECTION 4: CNN MODEL
# ============================================================================

class PneumoniaCNN(nn.Module):
    def __init__(self):
        super(PneumoniaCNN, self).__init__()

        # Convolutional layers
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(128, 256, kernel_size=3, padding=1)

        # Pooling and activation
        self.pool = nn.MaxPool2d(2, 2)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)

        # Fully connected layers
        self.fc1 = nn.Linear(256 * 14 * 14, 512)
        self.fc2 = nn.Linear(512, 128)
        self.fc3 = nn.Linear(128, 2)  # Binary classification

        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        # Conv block 1
        x = self.pool(self.relu(self.conv1(x)))
        # Conv block 2
        x = self.pool(self.relu(self.conv2(x)))
        # Conv block 3
        x = self.pool(self.relu(self.conv3(x)))
        # Conv block 4
        x = self.pool(self.relu(self.conv4(x)))

        # Flatten
        x = x.view(-1, 256 * 14 * 14)

        # Fully connected layers
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x)

        return x

# ============================================================================
# SECTION 5: CLASSIFIER CLASS
# ============================================================================

class PneumoniaClassifier:
    def __init__(self, img_size=224, device=None):
        self.img_size = img_size
        self.device = device if device else torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        # Data transforms
        self.train_transform = transforms.Compose([
            transforms.Resize((img_size, img_size)),
            transforms.RandomHorizontalFlip(),
            transforms.RandomRotation(10),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])

        self.val_transform = transforms.Compose([
            transforms.Resize((img_size, img_size)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])

        # Initialize model
        self.model = PneumoniaCNN().to(self.device)
        self.criterion = nn.CrossEntropyLoss()
        self.optimizer = optim.Adam(self.model.parameters(), lr=0.001)

        self.train_losses = []
        self.val_losses = []
        self.train_accs = []
        self.val_accs = []

    def load_data(self, train_dir, val_dir, batch_size=32):
        """Load training and validation datasets"""
        train_dataset = ChestXrayDataset(train_dir, transform=self.train_transform)
        val_dataset = ChestXrayDataset(val_dir, transform=self.val_transform)

        self.train_loader = DataLoader(train_dataset, batch_size=batch_size,
                                      shuffle=True, num_workers=2)
        self.val_loader = DataLoader(val_dataset, batch_size=batch_size,
                                    shuffle=False, num_workers=2)

        print(f"Training samples: {len(train_dataset)}")
        print(f"Validation samples: {len(val_dataset)}")

    def train_epoch(self):
        """Train for one epoch"""
        self.model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for images, labels in self.train_loader:
            images, labels = images.to(self.device), labels.to(self.device)

            # Forward pass
            self.optimizer.zero_grad()
            outputs = self.model(images)
            loss = self.criterion(outputs, labels)

            # Backward pass
            loss.backward()
            self.optimizer.step()

            # Statistics
            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        epoch_loss = running_loss / len(self.train_loader)
        epoch_acc = 100 * correct / total

        return epoch_loss, epoch_acc

    def validate(self):
        """Validate the model"""
        self.model.eval()
        running_loss = 0.0
        correct = 0
        total = 0

        with torch.no_grad():
            for images, labels in self.val_loader:
                images, labels = images.to(self.device), labels.to(self.device)

                outputs = self.model(images)
                loss = self.criterion(outputs, labels)

                running_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        epoch_loss = running_loss / len(self.val_loader)
        epoch_acc = 100 * correct / total

        return epoch_loss, epoch_acc

    def train(self, epochs=10):
        """Train the model"""
        print(f"Training on device: {self.device}")
        print("-" * 60)

        for epoch in range(epochs):
            train_loss, train_acc = self.train_epoch()
            val_loss, val_acc = self.validate()

            self.train_losses.append(train_loss)
            self.val_losses.append(val_loss)
            self.train_accs.append(train_acc)
            self.val_accs.append(val_acc)

            print(f"Epoch [{epoch+1}/{epochs}]")
            print(f"  Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%")
            print(f"  Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")
            print("-" * 60)

    def evaluate(self, test_dir):
        """Evaluate model on test set"""
        test_dataset = ChestXrayDataset(test_dir, transform=self.val_transform)
        test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

        self.model.eval()
        all_preds = []
        all_labels = []

        with torch.no_grad():
            for images, labels in test_loader:
                images = images.to(self.device)
                outputs = self.model(images)
                _, predicted = torch.max(outputs.data, 1)

                all_preds.extend(predicted.cpu().numpy())
                all_labels.extend(labels.numpy())

        # Calculate metrics
        accuracy = accuracy_score(all_labels, all_preds)
        precision, recall, f1, _ = precision_recall_fscore_support(
            all_labels, all_preds, average='binary'
        )
        cm = confusion_matrix(all_labels, all_preds)

        print("\n" + "=" * 60)
        print("TEST SET EVALUATION")
        print("=" * 60)
        print(f"Accuracy: {accuracy*100:.2f}%")
        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1-Score: {f1:.4f}")
        print(f"\nConfusion Matrix:\n{cm}")
        print("=" * 60)

        return accuracy, precision, recall, f1, cm

    def predict(self, image_path):
        """Predict on a single image"""
        self.model.eval()

        image = Image.open(image_path).convert('RGB')
        image = self.val_transform(image).unsqueeze(0).to(self.device)

        with torch.no_grad():
            output = self.model(image)
            probabilities = torch.softmax(output, dim=1)
            _, predicted = torch.max(output, 1)

        class_names = ['NORMAL', 'NORMAL']
        prediction = class_names[predicted.item()]
        confidence = probabilities[0][predicted.item()].item()

        return prediction, confidence

    def visualize_predictions(self, test_dir, num_images=8):
        """Visualize predictions on random test images"""
        test_dataset = ChestXrayDataset(test_dir, transform=self.val_transform)
        class_names = ['NORMAL', 'PNEUMONIA']

        # Get random samples
        indices = np.random.choice(len(test_dataset), num_images, replace=False)

        fig, axes = plt.subplots(2, 4, figsize=(16, 8))
        axes = axes.ravel()

        for idx, img_idx in enumerate(indices):
            image, true_label = test_dataset[img_idx]

            # Make prediction
            self.model.eval()
            with torch.no_grad():
                output = self.model(image.unsqueeze(0).to(self.device))
                probabilities = torch.softmax(output, dim=1)
                _, predicted = torch.max(output, 1)

            # Denormalize image for display
            img = image.permute(1, 2, 0).numpy()
            img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
            img = np.clip(img, 0, 1)

            # Display
            axes[idx].imshow(img)
            pred_label = class_names[predicted.item()]
            true_label_name = class_names[true_label]
            confidence = probabilities[0][predicted.item()].item() * 100

            color = 'green' if predicted.item() == true_label else 'red'
            axes[idx].set_title(f'Pred: {pred_label} ({confidence:.1f}%)\nTrue: {true_label_name}',
                               color=color)
            axes[idx].axis('off')

        plt.tight_layout()
        plt.show()

    def save_model(self, path='pneumonia_model.pth'):
        """Save model checkpoint"""
        torch.save({
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'train_losses': self.train_losses,
            'val_losses': self.val_losses,
            'train_accs': self.train_accs,
            'val_accs': self.val_accs
        }, path)
        print(f"Model saved to {path}")

    def load_model(self, path='pneumonia_model.pth'):
        """Load model checkpoint"""
        checkpoint = torch.load(path, map_location=self.device)
        self.model.load_state_dict(checkpoint['model_state_dict'])
        self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        self.train_losses = checkpoint['train_losses']
        self.val_losses = checkpoint['val_losses']
        self.train_accs = checkpoint['train_accs']
        self.val_accs = checkpoint['val_accs']
        print(f"Model loaded from {path}")

    def plot_training_history(self):
        """Plot training history"""
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

        # Plot losses
        ax1.plot(self.train_losses, label='Train Loss')
        ax1.plot(self.val_losses, label='Val Loss')
        ax1.set_xlabel('Epoch')
        ax1.set_ylabel('Loss')
        ax1.set_title('Training and Validation Loss')
        ax1.legend()
        ax1.grid(True)

        # Plot accuracies
        ax2.plot(self.train_accs, label='Train Acc')
        ax2.plot(self.val_accs, label='Val Acc')
        ax2.set_xlabel('Epoch')
        ax2.set_ylabel('Accuracy (%)')
        ax2.set_title('Training and Validation Accuracy')
        ax2.legend()
        ax2.grid(True)

        plt.tight_layout()
        plt.show()

# ============================================================================
# SECTION 6: COLAB EXECUTION EXAMPLE
# ============================================================================

# Check GPU availability
print("=" * 60)
print("SYSTEM INFO")
print("=" * 60)
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")
print("=" * 60)

print("\n✅ Pneumonia Classifier ready for Google Colab!")
print("📋 Uncomment the example workflow code to start training")